name: Memories App Client Deploye

on:
  push:
    branches: ['main']

jobs:
  deploy-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: SSH to server for deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |-
            sudo apt-get update
            sudo apt-get install git -y
            echo "--NODE & NPM--"
            sudo apt install nodejs -y
            sudo apt install npm -y
            echo "-----PM2------"
            sudo npm install -g pm2
            sudo pm2 startup systemd
            echo "-----NGINX------"
            sudo apt-get install -y nginx
            echo "---FIREWALL---"
            sudo ufw allow OpenSSH
            sudo ufw allow 'Nginx Full'
            sudo ufw --force enable 
            cd /home/ubuntu
            sudo rm -rf memoryapp-client || true
            git clone https://github.com/Eunice2000/memoryapp-client.git
            cd memoryapp-client
            npm install
            rm -rf build
            npm run build
            pm2 delete react-build || true
            sudo killall -9 node || true
            pm2 serve build/ 3000 -f --name "react-build" --spa
            sudo rm -rf /etc/nginx/sites-available/default
            sudo cp default /etc/nginx/sites-available/ -r
            sudo systemctl stop nginx
            sudo systemctl kill nginx || true
            sudo systemctl start nginx
            
